import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { ArrowRight, ShieldCheck, FileCheck } from "lucide-react";
import { listTailoredVersions } from "../../lib/tailoring";
import { ResumeDiffModal } from "../../components/resume/ResumeDiffModal";

export function TailoredVersions() {
  const { data, isLoading } = useQuery({ queryKey: ["tailoring-list"], queryFn: listTailoredVersions });

  return (
    <div className="max-w-3xl">
      <div className="flex items-center justify-between mb-2">
        <h1 className="font-display text-2xl text-ink-900">Tailored Versions</h1>
        <span className="text-xs font-semibold text-signal-700 bg-signal-500/10 px-2.5 py-1 rounded-full flex items-center gap-1">
          <ShieldCheck size={13} /> Truth Guard Protected
        </span>
      </div>
      <p className="text-ink-500 mb-6 text-sm">
        Every company-specific resume version generated by RoleRadar. Your master resume is never modified by any tailoring pass.
      </p>

      {isLoading && <p className="text-ink-500">Loading tailored versions…</p>}
      {!isLoading && data?.length === 0 && (
        <div className="rounded-xl border border-ink-100 bg-white p-8 text-center">
          <FileCheck size={32} className="mx-auto text-ink-300 mb-2" />
          <p className="text-sm font-medium text-ink-700 mb-1">No tailored versions yet</p>
          <p className="text-xs text-ink-500 mb-4">Go to Jobs For You to tailor your master resume for an open opportunity.</p>
          <Link
            to="/opportunities/jobs"
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg bg-ink-950 text-white text-xs font-semibold hover:bg-ink-900"
          >
            Explore Jobs & Tailor <ArrowRight size={13} />
          </Link>
        </div>
      )}

      <div className="space-y-3">
        {data?.map((v) => {
          const approved = v.changes.filter((c) => c.status === "APPROVED").length;
          return (
            <div
              key={v.id}
              className="rounded-xl border border-ink-100 bg-white p-5 hover:border-signal-500 hover:shadow-xs transition-all flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
            >
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="font-display font-semibold text-ink-900">{v.job_title}</span>
                  <span className="text-xs text-ink-400">•</span>
                  <span className="text-sm text-ink-600 font-medium">{v.company}</span>
                  <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase ${
                    v.is_finalized
                      ? "bg-signal-500/10 text-signal-700 border border-signal-500/20"
                      : "bg-amber-500/10 text-amber-700 border border-amber-500/20"
                  }`}>
                    {v.is_finalized ? "Finalized" : "Draft"}
                  </span>
                </div>
                <p className="text-xs text-ink-500">
                  Tailored on {new Date(v.created_at).toLocaleDateString()} • {approved}/{v.changes.length} approved changes with Truth Guard verification
                </p>
              </div>

              <div className="flex items-center gap-2 shrink-0 self-end sm:self-center">
                <ResumeDiffModal version={v} />
                <Link
                  to={`/resume/tailor/${v.job_id}?version=${v.id}`}
                  className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg bg-ink-950 hover:bg-ink-900 text-white text-xs font-semibold transition-colors"
                >
                  Review & Export <ArrowRight size={12} />
                </Link>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
