import { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  ArrowRight, Trash2, Loader2, Copy, Sparkles, Eye,
  FileText, FileCode2, Download, CheckCircle2, XCircle, Target, GitCompare, ShieldCheck,
} from "lucide-react";
import { listTailoredVersions, deleteTailoredVersion } from "../../lib/tailoring";
import { ResumeDiffModal } from "../../components/resume/ResumeDiffModal";
import { ResumePreviewModal } from "../../components/resume/ResumePreviewModal";
import { useToast } from "../../context/ToastContext";
import { SkeletonCard } from "../../components/ui/SkeletonLoaders";

// ── Inline export button ──────────────────────────────────────────────────────
function DownloadButton({
  versionId,
  company,
  format,
}: {
  versionId: string;
  company: string;
  format: "pdf" | "docx";
}) {
  const [isDownloading, setIsDownloading] = useState(false);
  const toast = useToast();

  const handleDownload = async () => {
    setIsDownloading(true);
    try {
      const token =
        localStorage.getItem("roleradar_token") ||
        sessionStorage.getItem("roleradar_token");
      const res = await fetch(
        `/api/tailoring/${versionId}/export/${format}?template=modern`,
        { headers: token ? { Authorization: `Bearer ${token}` } : {} }
      );
      if (!res.ok) throw new Error(`Export failed: ${res.statusText}`);
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `resume_${company.replace(/\s+/g, "_")}.${format}`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
      toast.success(`${format.toUpperCase()} downloaded successfully.`);
    } catch (err: any) {
      toast.error(err.message || `Failed to download ${format.toUpperCase()}.`);
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <button
      type="button"
      onClick={handleDownload}
      disabled={isDownloading}
      title={`Download tailored resume as ${format.toUpperCase()}`}
      className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-2 text-[11px] font-semibold shadow-2xs transition-all disabled:cursor-not-allowed disabled:opacity-60 ${
        format === "pdf"
          ? "border-rose-200 bg-rose-50/70 text-rose-800 hover:border-rose-300 hover:bg-rose-100"
          : "border-blue-200 bg-blue-50/70 text-blue-800 hover:border-blue-300 hover:bg-blue-100"
      }`}
    >
      {isDownloading ? (
        <Loader2 size={12} className="animate-spin" />
      ) : format === "pdf" ? (
        <FileText size={12} className="text-rose-500" />
      ) : (
        <FileCode2 size={12} className="text-indigo-500" />
      )}
      <span>{format.toUpperCase()}</span>
    </button>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────
export function TailoredVersions() {
  const queryClient = useQueryClient();
  const toast = useToast();
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);

  const { data, isLoading } = useQuery({ queryKey: ["tailoring-list"], queryFn: listTailoredVersions });

  const deleteMutation = useMutation({
    mutationFn: (versionId: string) => deleteTailoredVersion(versionId),
    onSuccess: () => {
      setConfirmDeleteId(null);
      queryClient.invalidateQueries({ queryKey: ["tailoring-list"] });
      toast.info("Tailored resume version deleted.");
    },
    onError: () => toast.error("Failed to delete tailored version."),
  });

  return (
    <div className="mx-auto w-full min-w-0 max-w-6xl space-y-5 animate-fade-in-up">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className="p-1 rounded-md bg-signal-500/10 text-signal-700">
              <Copy size={15} />
            </span>
            <h1 className="font-display text-xl sm:text-2xl font-bold text-ink-950">
              Tailored Resume Versions
            </h1>
          </div>
          <p className="text-xs sm:text-sm text-ink-500">
            Every company-specific resume generated by RoleRadar with Truth Guard anti-hallucination protection.
          </p>
        </div>

        <div className="flex shrink-0 flex-wrap items-center gap-2 self-start sm:self-auto">
          <Link
            to="/resume/tailor-custom"
            className="inline-flex h-10 items-center gap-1.5 rounded-xl border border-slate-300 bg-white px-3.5 text-xs font-semibold text-ink-700 shadow-2xs transition-colors hover:border-slate-400 hover:bg-slate-50"
          >
            <FileText size={13} />
            <span>Custom JD</span>
          </Link>
          <Link
            to="/opportunities/jobs"
            className="inline-flex h-10 items-center gap-1.5 rounded-xl bg-signal-600 px-3.5 text-xs font-semibold text-white shadow-xs transition-colors hover:bg-signal-700"
          >
            <Sparkles size={13} />
            <span>Tailor for a Job</span>
          </Link>
        </div>
      </div>

      {isLoading ? (
        <SkeletonCard count={3} />
      ) : data?.length === 0 ? (
        <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-5 py-12 text-center shadow-sm">
          <span className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-2xl border border-signal-500/20 bg-signal-500/10 text-signal-700">
            <Copy size={22} />
          </span>
          <h2 className="font-display text-lg font-bold text-ink-900">No tailored versions yet</h2>
          <p className="mx-auto mt-1 max-w-lg text-sm leading-relaxed text-ink-500">
            Tailor your master resume for a job to create a company-aligned version with ATS feedback and Truth Guard review.
          </p>
          <div className="mt-5 flex flex-wrap justify-center gap-2">
            <Link
              to="/opportunities/jobs"
              className="inline-flex h-10 items-center justify-center gap-1.5 rounded-lg bg-signal-600 px-4 text-xs font-semibold text-white shadow-xs transition-colors hover:bg-signal-700"
            >
              <Sparkles size={14} />
              Tailor for a Job
              <ArrowRight size={13} />
            </Link>
            <Link
              to="/resume/tailor-custom"
              className="inline-flex h-10 items-center justify-center gap-1.5 rounded-lg border border-slate-300 bg-white px-4 text-xs font-semibold text-ink-700 transition-colors hover:bg-slate-50"
            >
              <FileText size={14} />
              Use a Custom JD
            </Link>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 items-start gap-4 xl:grid-cols-2">
          {data?.map((v) => {
            const approved = v.changes.filter((c) => c.status === "APPROVED").length;
            const pending = v.changes.filter((c) => c.status === "PENDING").length;
            const isDeleting = deleteMutation.isPending && deleteMutation.variables === v.id;
            const isConfirming = confirmDeleteId === v.id;

            const matchedCount = v.matched_skills?.length ?? 0;
            const missingCount = v.missing_skills?.length ?? 0;
            const atsScore = (v.tailored_scores as any)?.ats_score ?? null;

            return (
              <div
                key={v.id}
                className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition-all hover:border-signal-500/35 hover:shadow-md"
              >
                {/* Card body */}
                  <div className="p-4 sm:p-5">
                    <div className="flex items-start justify-between gap-3">
                      <div className="min-w-0">
                        <h2 className="truncate font-display text-base font-bold text-ink-950">{v.job_title}</h2>
                        <p className="mt-1 text-sm font-medium text-ink-600">{v.company}</p>
                        <p className="mt-1 text-[11px] text-ink-500">
                          Created {new Date(v.created_at).toLocaleDateString("en-IN", {
                            day: "numeric", month: "short", year: "numeric",
                          })}
                        </p>
                      </div>
                      <span className={`shrink-0 rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${
                        v.is_finalized
                          ? "border-emerald-200 bg-emerald-50 text-emerald-700"
                          : "border-amber-200 bg-amber-50 text-amber-800"
                      }`}>
                        {v.is_finalized ? "Finalized" : "Draft"}
                      </span>
                    </div>

                    <div className="mt-3 flex flex-wrap items-center gap-2">
                      {v.validation_summary?.anti_fabrication_passed && (
                        <span className="inline-flex items-center gap-1 rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-[10px] font-semibold text-emerald-700">
                          <ShieldCheck size={11} />
                          Truth Guard Verified
                        </span>
                      )}
                      <span className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-[10px] font-semibold text-slate-700">
                        <CheckCircle2 size={11} className="text-emerald-600" />
                        {approved}/{v.changes.length} changes approved
                      </span>
                      {pending > 0 && (
                        <span className="rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 text-[10px] font-semibold text-amber-800">
                          {pending} pending
                        </span>
                      )}
                    </div>

                    {/* Skills & ATS score summary row */}
                    <div className="mt-3 flex flex-wrap items-center gap-2">
                        {atsScore !== null && (
                          <span className="inline-flex items-center gap-1 text-[11px] font-semibold text-signal-700 bg-signal-500/10 border border-signal-500/20 px-2 py-0.5 rounded-full">
                            <Target size={11} />
                            ATS {atsScore}%
                          </span>
                        )}
                        {matchedCount > 0 && (
                          <span className="inline-flex items-center gap-1 text-[11px] font-medium text-emerald-700 bg-emerald-50 border border-emerald-200 px-2 py-0.5 rounded-full">
                            <CheckCircle2 size={11} />
                            {matchedCount} matched
                          </span>
                        )}
                        {missingCount > 0 && (
                          <span className="inline-flex items-center gap-1 text-[11px] font-medium text-rose-700 bg-rose-50 border border-rose-200 px-2 py-0.5 rounded-full">
                            <XCircle size={11} />
                            {missingCount} gaps
                          </span>
                        )}
                      </div>
                    </div>
                  {/* Card action bar */}
                  <div className="mx-4 mb-4 mt-3 flex flex-wrap items-center gap-2 border-t border-slate-100 pt-3 sm:mx-5">
                      {isConfirming ? (
                        <div className="flex items-center gap-1.5 rounded-xl border border-red-200 bg-red-50 px-2.5 py-1.5">
                          <span className="text-[11px] font-bold text-red-800">Delete this version?</span>
                          <button
                            type="button"
                            onClick={() => deleteMutation.mutate(v.id)}
                            disabled={isDeleting}
                            className="px-2 py-1 rounded-lg bg-red-600 hover:bg-red-700 text-white text-[11px] font-bold transition-colors flex items-center gap-1"
                          >
                            {isDeleting ? <Loader2 size={11} className="animate-spin" /> : "Delete"}
                          </button>
                          <button
                            type="button"
                            onClick={() => setConfirmDeleteId(null)}
                            disabled={isDeleting}
                            className="px-2 py-1 rounded-lg bg-white hover:bg-ink-100 border border-ink-200 text-ink-700 text-[11px] font-medium transition-colors"
                          >
                            Cancel
                          </button>
                        </div>
                      ) : (
                        <>
                          <ResumePreviewModal
                            versionId={v.id}
                            company={v.company}
                            jobTitle={v.job_title}
                            triggerButton={
                              <button
                                type="button"
                                className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-transparent bg-slate-50 px-3 text-xs font-semibold text-ink-700 transition-colors hover:border-slate-200 hover:bg-white"
                              >
                                <Eye size={13} className="text-signal-600" />
                                <span>Preview</span>
                              </button>
                            }
                          />
                          <ResumeDiffModal
                            version={v}
                            triggerButton={
                              <button
                                type="button"
                                className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-transparent bg-slate-50 px-3 text-xs font-semibold text-ink-700 transition-colors hover:border-slate-200 hover:bg-white"
                              >
                                <GitCompare size={13} className="text-ink-500" />
                                Compare Diff
                              </button>
                            }
                          />
                          <Link
                            to={`/resume/tailor/${v.job_id}?version=${v.id}`}
                            className="inline-flex h-9 items-center gap-1.5 rounded-lg bg-signal-600 px-3.5 text-xs font-bold text-white shadow-2xs transition-colors hover:bg-signal-700"
                          >
                            <span>{v.is_finalized ? "View & Export" : "Review"}</span>
                            <ArrowRight size={12} />
                          </Link>
                          <button
                            type="button"
                            onClick={() => setConfirmDeleteId(v.id)}
                            className="ml-auto inline-flex h-9 w-9 items-center justify-center rounded-lg text-ink-400 transition-colors hover:bg-red-50 hover:text-red-600"
                            title="Delete this tailored version"
                            aria-label={`Delete tailored resume for ${v.job_title} at ${v.company}`}
                          >
                            <Trash2 size={15} />
                          </button>
                        </>
                      )}
                  </div>

                {/* Download footer strip */}
                {!isConfirming && (
                  <div className="flex flex-wrap items-center gap-2 border-t border-slate-200 bg-slate-50/70 px-4 py-3 sm:px-5">
                    <Download size={12} className="text-ink-400" />
                    <span className="mr-1 text-[11px] font-medium text-ink-500">Download tailored resume</span>
                    <DownloadButton versionId={v.id} company={v.company} format="pdf" />
                    <DownloadButton versionId={v.id} company={v.company} format="docx" />
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
