import { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, Trash2, Loader2, Copy, Sparkles } from "lucide-react";
import { listTailoredVersions, deleteTailoredVersion } from "../../lib/tailoring";
import { ResumeDiffModal } from "../../components/resume/ResumeDiffModal";
import { useToast } from "../../context/ToastContext";
import { EmptyState } from "../../components/ui/EmptyState";
import { SkeletonCard } from "../../components/ui/SkeletonLoaders";

export function TailoredVersions() {
  const queryClient = useQueryClient();
  const toast = useToast();
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);

  const { data, isLoading } = useQuery({ queryKey: ["tailoring-list"], queryFn: listTailoredVersions });

  const deleteMutation = useMutation({
    mutationFn: (versionId: string) => deleteTailoredVersion(versionId),
    onSuccess: () => {
      setConfirmDeleteId(null);
      queryClient.invalidateQueries({ queryKey: ["tailoring-list"] });
      toast.info("Tailored resume version deleted.");
    },
    onError: () => toast.error("Failed to delete tailored version."),
  });

  return (
    <div className="max-w-4xl space-y-6 animate-fade-in-up">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="p-1 rounded-md bg-signal-500/10 text-signal-700">
              <Copy size={15} />
            </span>
            <h1 className="font-display text-xl sm:text-2xl font-bold text-ink-950">
              Tailored Resume Versions
            </h1>
          </div>
          <p className="text-xs sm:text-sm text-ink-500">
            Every company-specific resume version generated by RoleRadar with Truth Guard anti-hallucination protection.
          </p>
        </div>

        <Link
          to="/opportunities/jobs"
          className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-signal-500 hover:bg-signal-600 text-white text-xs font-semibold shadow-xs transition-colors shrink-0 self-start sm:self-auto"
        >
          <Sparkles size={13} />
          <span>Tailor for a Job</span>
        </Link>
      </div>

      {isLoading ? (
        <SkeletonCard count={3} />
      ) : data?.length === 0 ? (
        <EmptyState
          icon={Copy}
          title="No tailored versions created yet"
          description="Tailor your master resume for any job opening to generate verified, company-aligned versions with ATS scoring feedback."
          actionText="Browse Job Openings"
          actionHref="/opportunities/jobs"
          secondaryActionText="Custom JD Tailoring"
          secondaryActionHref="/resume/tailor-custom"
        />
      ) : (
        <div className="space-y-3">
          {data?.map((v) => {
            const approved = v.changes.filter((c) => c.status === "APPROVED").length;
            const isDeleting = deleteMutation.isPending && deleteMutation.variables === v.id;
            const isConfirming = confirmDeleteId === v.id;

            return (
              <div
                key={v.id}
                className="rounded-2xl border border-ink-100 bg-white p-5 hover:border-signal-500/40 hover:shadow-md transition-all flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
              >
                <div className="flex-1 min-w-0 space-y-1">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <span className="font-display font-bold text-ink-950 truncate text-sm">
                      {v.job_title}
                    </span>
                    <span className="text-xs text-ink-400">•</span>
                    <span className="text-xs text-ink-600 font-medium">{v.company}</span>
                    <span
                      className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase ${
                        v.is_finalized
                          ? "bg-signal-500/10 text-signal-700 border border-signal-500/20"
                          : "bg-amber-500/10 text-amber-700 border border-amber-500/20"
                      }`}
                    >
                      {v.is_finalized ? "Finalized" : "Draft"}
                    </span>
                  </div>
                  <p className="text-xs text-ink-500">
                    Created on {new Date(v.created_at).toLocaleDateString()} • {approved}/{v.changes.length} approved changes • Truth Guard verified
                  </p>
                </div>

                <div className="flex items-center gap-2 shrink-0 self-end sm:self-center">
                  {isConfirming ? (
                    <div className="flex items-center gap-1.5 bg-alert-50 border border-alert-200 px-2.5 py-1 rounded-xl">
                      <span className="text-[11px] font-bold text-alert-800">Delete version?</span>
                      <button
                        type="button"
                        onClick={() => deleteMutation.mutate(v.id)}
                        disabled={isDeleting}
                        className="px-2 py-1 rounded-lg bg-alert-600 hover:bg-alert-700 text-white text-[11px] font-bold transition-colors flex items-center gap-1"
                      >
                        {isDeleting ? <Loader2 size={11} className="animate-spin" /> : "Delete"}
                      </button>
                      <button
                        type="button"
                        onClick={() => setConfirmDeleteId(null)}
                        disabled={isDeleting}
                        className="px-2 py-1 rounded-lg bg-white hover:bg-ink-100 border border-ink-200 text-ink-700 text-[11px] font-medium transition-colors"
                      >
                        Cancel
                      </button>
                    </div>
                  ) : (
                    <>
                      <ResumeDiffModal version={v} />
                      <Link
                        to={`/resume/tailor/${v.job_id}?version=${v.id}`}
                        className="inline-flex items-center gap-1 text-xs font-semibold text-white bg-ink-950 hover:bg-ink-900 px-3 py-1.5 rounded-lg shadow-2xs transition-colors"
                      >
                        <span>{v.is_finalized ? "View & Export" : "Review Proposal"}</span>
                        <ArrowRight size={12} />
                      </Link>
                      <button
                        type="button"
                        onClick={() => setConfirmDeleteId(v.id)}
                        className="p-1.5 rounded-lg text-ink-400 hover:text-alert-600 hover:bg-alert-50 transition-colors"
                        title="Delete this tailored version"
                        aria-label="Delete this tailored version"
                      >
                        <Trash2 size={15} />
                      </button>
                    </>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
