from pydantic import BaseModel


class JobMatchOut(BaseModel):
    job_id: str
    job_title: str
    company: str
    source_id: str | None = None
    internal_source: str | None = None
    overall_score: int | None = None
    skill_score: int | None = None
    role_score: int | None = None
    experience_score: int | None = None
    location_score: int | None = None
    salary_score: int | None = None
    industry_score: int | None = None
    experience_min: float | None = None
    experience_max: float | None = None
    experience_text: str | None = None
    matched_skills: list[str] = []
    partial_skills: list[str] = []
    missing_skills: list[str] = []
    skills_required: list[str] = []
    apply_readiness: str | None = None
    job_type: str | None = None
    employment_type: str | None = None
    source: str | None = None
    apply_url: str | None = None
    location: str | None = None
    is_remote: bool | None = None
    workplace_type: str | None = None
    country: str | None = None
    salary_min: float | None = None
    salary_max: float | None = None
    salary_disclosed: bool = False
    salary_currency: str | None = None
    salary_period: str | None = None
    salary_unit: str | None = None
    stipend: float | None = None
    stipend_min: float | None = None
    stipend_max: float | None = None
    stipend_currency: str | None = None
    stipend_period: str | None = None
    stipend_unit: str | None = None
    compensation_type: str | None = None
    compensation_text: str | None = None
    posted_days_ago: int | None = None
    created_at: str | None = None
    posted_at: str | None = None
    updated_at: str | None = None
    registration_closing_date: str | None = None
    application_deadline: str | None = None
    end_date: str | None = None
    has_match: bool | None = None
    source_job_id: str | None = None
    source_url: str | None = None
    verification_status: str | None = None
    verified_at: str | None = None
    last_verified_at: str | None = None
    verification_reason: str | None = None
    verification_method: str | None = None
    url_type: str | None = None
    is_direct_apply: bool | None = None
    opportunity_type: str | None = None
    candidate_suitability: str | None = None
    student_eligible: bool | None = None
    fresher_eligible: bool | None = None
    eligibility_text: str | None = None
    degree_requirements: list[str] = []
    graduation_year_requirements: list[int] = []
    eligibility: dict | None = None
    realistic_fit: str | None = None
    fit_explanation: str | None = None
    factor_weights: dict[str, float] | None = None
    score_explanation: str | None = None
    canonical_role: str | None = None
    canonical_role_key: str | None = None
    role_domain: str | None = None
    contextual_requirements: list[str] = []
    quality_tier: str | None = None
    role_confidence: str | None = None
    recommendation_quality: str | None = None
    seniority: str | None = None